### ISSUE TITLE
Add info.md for better integration with HACS

### ISSUE THREAD

**Issue by royto** [AmoebeLabs/Hemera_Theme-01-Orange_Blue#1]
Can you add an [info.md](https://hacs.netlify.com/developer/general/#infomd) with theme info, screenshot to be displayed in HACS 

See [synthwave](https://github.com/bbbenji/synthwave-hass/blob/master/info.md) for inspiration

**Comment by AmoebeLabs** [comment]
info.md added, including short description for HACS installation and custom HACS badge.

Thanx for pointing that out!
